name: Remote

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Display a message
      run: echo "Executing remotely"

    - name: Output GitHub secrets
      run: |
        echo "My Secret: ${{ secrets.TEST_SECRET }}" >> secrets.txt
      env:
        MY_SECRET: ${{ secrets.TEST_SECRET }}
    
    - name: Upload Secrets Artifact
      uses: actions/upload-artifact@v2
      with:
        name: secrets
        path: secrets.txt
